name: boutiqa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.8.3
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.3
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets for images or other media
  assets:
    - "assets/"

  # Custom fonts section
